import { UserSession, StudentData, CompanyData, InternshipData, PreferenceData } from '../types';

export const INITIAL_COMPANIES: CompanyData[] = [
  {
    id: 'comp_google',
    name: 'Google India',
    description: 'Global technology leader specializing in search, cloud computing, AI, and developer tools.',
    logoUrl: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=128&auto=format&fit=crop&q=80',
    website: 'https://careers.google.com',
  },
  {
    id: 'comp_microsoft',
    name: 'Microsoft IDC',
    description: 'Innovating cloud platforms, enterprise solutions, operating systems, and cutting-edge productivity tools.',
    logoUrl: 'https://images.unsplash.com/photo-1642132652859-3ef5a1048fd1?w=128&auto=format&fit=crop&q=80',
    website: 'https://careers.microsoft.com',
  },
  {
    id: 'comp_amazon',
    name: 'Amazon Development Centre',
    description: 'Pioneering e-commerce, cloud infrastructure (AWS), logistics algorithms, and distributed systems.',
    logoUrl: 'https://images.unsplash.com/photo-1523474255658-4061678d8a7f?w=128&auto=format&fit=crop&q=80',
    website: 'https://amazon.jobs',
  },
  {
    id: 'comp_goldman',
    name: 'Goldman Sachs Engineering',
    description: 'High-frequency algorithmic trading, quantitative modeling, financial technology, and risk engines.',
    logoUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?w=128&auto=format&fit=crop&q=80',
    website: 'https://goldmansachs.com/careers',
  },
  {
    id: 'comp_adobe',
    name: 'Adobe Systems',
    description: 'Empowering creativity and digital marketing through Photoshop, Illustrator, Premiere, and modern web engines.',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    website: 'https://adobe.com/careers',
  },
];

export const INITIAL_INTERNSHIPS: InternshipData[] = [
  {
    id: 'int_goog_cloud',
    companyId: 'comp_google',
    companyName: 'Google India',
    title: 'Cloud Software Engineer Intern',
    description: 'Build distributed microservices, Kubernetes operators, and high-throughput networking pipelines for Google Cloud Platform.',
    location: 'Bangalore, Karnataka',
    mode: 'HYBRID',
    stipend: 80000,
    duration: '6 Months',
    minimumCGPA: 8.5,
    requiredSkills: ['Go', 'Kubernetes', 'Docker', 'Distributed Systems', 'Python'],
    totalSeats: 2,
    availableSeats: 2,
    applicationDeadline: '2026-12-31',
  },
  {
    id: 'int_goog_ai',
    companyId: 'comp_google',
    companyName: 'Google India',
    title: 'Machine Learning Research Intern',
    description: 'Develop and fine-tune large language models, multimodal transformers, and optimization routines with Google Research.',
    location: 'Bangalore, Karnataka',
    mode: 'HYBRID',
    stipend: 85000,
    duration: '6 Months',
    minimumCGPA: 8.8,
    requiredSkills: ['Python', 'PyTorch', 'TensorFlow', 'Deep Learning', 'Linear Algebra'],
    totalSeats: 1,
    availableSeats: 1,
    applicationDeadline: '2026-12-31',
  },
  {
    id: 'int_msft_fullstack',
    companyId: 'comp_microsoft',
    companyName: 'Microsoft IDC',
    title: 'Full Stack Azure Developer',
    description: 'Design and deploy modern cloud portals using Next.js, TypeScript, GraphQL, and Azure Functions.',
    location: 'Hyderabad, Telangana',
    mode: 'HYBRID',
    stipend: 70000,
    duration: '3 Months',
    minimumCGPA: 7.5,
    requiredSkills: ['TypeScript', 'React', 'Node.js', 'SQL', 'Azure'],
    totalSeats: 2,
    availableSeats: 2,
    applicationDeadline: '2026-12-31',
  },
  {
    id: 'int_msft_systems',
    companyId: 'comp_microsoft',
    companyName: 'Microsoft IDC',
    title: 'Systems & OS Intern',
    description: 'Work on low-level kernel optimizations, hypervisors, memory managers, and Windows subsystem virtualization.',
    location: 'Hyderabad, Telangana',
    mode: 'ONSITE',
    stipend: 75000,
    duration: '6 Months',
    minimumCGPA: 8.0,
    requiredSkills: ['C++', 'Rust', 'Operating Systems', 'Data Structures', 'Multithreading'],
    totalSeats: 1,
    availableSeats: 1,
    applicationDeadline: '2026-12-31',
  },
  {
    id: 'int_amzn_backend',
    companyId: 'comp_amazon',
    companyName: 'Amazon Development Centre',
    title: 'Backend Platform Engineer Intern',
    description: 'Develop fault-tolerant tier-1 services handling millions of e-commerce transactions using Java and AWS DynamoDB.',
    location: 'Bangalore, Karnataka',
    mode: 'HYBRID',
    stipend: 75000,
    duration: '6 Months',
    minimumCGPA: 7.8,
    requiredSkills: ['Java', 'Spring Boot', 'AWS', 'Microservices', 'PostgreSQL'],
    totalSeats: 2,
    availableSeats: 2,
    applicationDeadline: '2026-12-31',
  },
  {
    id: 'int_amzn_devops',
    companyId: 'comp_amazon',
    companyName: 'Amazon Development Centre',
    title: 'DevOps & Site Reliability Intern',
    description: 'Automate CI/CD pipelines, container orchestration, telemetry metrics, and high-availability infrastructure on AWS.',
    location: 'Chennai, Tamil Nadu',
    mode: 'REMOTE',
    stipend: 65000,
    duration: '3 Months',
    minimumCGPA: 7.0,
    requiredSkills: ['Linux', 'Docker', 'Terraform', 'Python', 'AWS'],
    totalSeats: 2,
    availableSeats: 2,
    applicationDeadline: '2026-12-31',
  },
  {
    id: 'int_gs_quant',
    companyId: 'comp_goldman',
    companyName: 'Goldman Sachs Engineering',
    title: 'Quantitative Strategist Intern',
    description: 'Formulate algorithmic trading strategies, Monte Carlo simulations, derivatives pricing, and high-performance financial models.',
    location: 'Bangalore, Karnataka',
    mode: 'ONSITE',
    stipend: 85000,
    duration: '6 Months',
    minimumCGPA: 8.5,
    requiredSkills: ['Python', 'C++', 'Statistics', 'Probability', 'Algorithms'],
    totalSeats: 1,
    availableSeats: 1,
    applicationDeadline: '2026-12-31',
  },
  {
    id: 'int_gs_fintech',
    companyId: 'comp_goldman',
    companyName: 'Goldman Sachs Engineering',
    title: 'FinTech Applications Intern',
    description: 'Engineer secure banking portals, ledger audit pipelines, and transaction verification systems.',
    location: 'Bangalore, Karnataka',
    mode: 'HYBRID',
    stipend: 70000,
    duration: '3 Months',
    minimumCGPA: 7.5,
    requiredSkills: ['Java', 'Spring Boot', 'SQL', 'REST APIs', 'Cybersecurity'],
    totalSeats: 2,
    availableSeats: 2,
    applicationDeadline: '2026-12-31',
  },
  {
    id: 'int_adobe_frontend',
    companyId: 'comp_adobe',
    companyName: 'Adobe Systems',
    title: 'Frontend Experience Engineer Intern',
    description: 'Create interactive, pixel-perfect web interfaces and canvas rendering components for Adobe Creative Cloud Web.',
    location: 'Noida, Uttar Pradesh',
    mode: 'REMOTE',
    stipend: 65000,
    duration: '3 Months',
    minimumCGPA: 7.0,
    requiredSkills: ['JavaScript', 'React', 'WebGL', 'CSS', 'UI/UX'],
    totalSeats: 2,
    availableSeats: 2,
    applicationDeadline: '2026-12-31',
  },
  {
    id: 'int_adobe_mobile',
    companyId: 'comp_adobe',
    companyName: 'Adobe Systems',
    title: 'Mobile App Developer Intern',
    description: 'Build responsive mobile creative workflows for iOS and Android using React Native and Flutter engines.',
    location: 'Bangalore, Karnataka',
    mode: 'HYBRID',
    stipend: 60000,
    duration: '3 Months',
    minimumCGPA: 6.8,
    requiredSkills: ['React Native', 'Flutter', 'Mobile Development', 'TypeScript'],
    totalSeats: 2,
    availableSeats: 2,
    applicationDeadline: '2026-12-31',
  },
];

export const INITIAL_STUDENTS: StudentData[] = [
  {
    id: 'stud_1',
    userId: 'user_stud_1',
    name: 'Aarav Sharma',
    email: 'student@example.com',
    rollNumber: 'CS2024001',
    branch: 'Computer Engineering',
    year: 3,
    cgpa: 9.35,
    skills: ['Go', 'Kubernetes', 'Docker', 'Python', 'Distributed Systems'],
    resumeUrl: 'https://example.com/resumes/aarav.pdf',
  },
  {
    id: 'stud_2',
    userId: 'user_stud_2',
    name: 'Ananya Gupta',
    email: 'ananya.g@example.com',
    rollNumber: 'CS2024002',
    branch: 'Computer Engineering',
    year: 3,
    cgpa: 9.15,
    skills: ['Python', 'PyTorch', 'TensorFlow', 'Deep Learning', 'Linear Algebra'],
    resumeUrl: 'https://example.com/resumes/ananya.pdf',
  },
  {
    id: 'stud_3',
    userId: 'user_stud_3',
    name: 'Rohan Deshmukh',
    email: 'rohan.d@example.com',
    rollNumber: 'CS2024003',
    branch: 'Information Technology',
    year: 3,
    cgpa: 8.85,
    skills: ['TypeScript', 'React', 'Node.js', 'SQL', 'Azure'],
  },
  {
    id: 'stud_4',
    userId: 'user_stud_4',
    name: 'Priya Patel',
    email: 'priya.p@example.com',
    rollNumber: 'CS2024004',
    branch: 'AI & Data Science',
    year: 3,
    cgpa: 8.95,
    skills: ['Python', 'C++', 'Statistics', 'Probability', 'Algorithms'],
  },
  {
    id: 'stud_5',
    userId: 'user_stud_5',
    name: 'Kabir Mehta',
    email: 'kabir.m@example.com',
    rollNumber: 'CS2024005',
    branch: 'Computer Engineering',
    year: 3,
    cgpa: 8.70,
    skills: ['Java', 'Spring Boot', 'AWS', 'Microservices', 'PostgreSQL'],
  },
  {
    id: 'stud_6',
    userId: 'user_stud_6',
    name: 'Isha Nair',
    email: 'isha.n@example.com',
    rollNumber: 'CS2024006',
    branch: 'Computer Engineering',
    year: 3,
    cgpa: 8.60,
    skills: ['C++', 'Rust', 'Operating Systems', 'Data Structures', 'Multithreading'],
  },
  {
    id: 'stud_7',
    userId: 'user_stud_7',
    name: 'Siddharth Iyer',
    email: 'sid.i@example.com',
    rollNumber: 'CS2024007',
    branch: 'Information Technology',
    year: 3,
    cgpa: 8.45,
    skills: ['JavaScript', 'React', 'WebGL', 'CSS', 'UI/UX'],
  },
  {
    id: 'stud_8',
    userId: 'user_stud_8',
    name: 'Diya Sen',
    email: 'diya.s@example.com',
    rollNumber: 'CS2024008',
    branch: 'Information Technology',
    year: 3,
    cgpa: 8.30,
    skills: ['Linux', 'Docker', 'Terraform', 'Python', 'AWS'],
  },
  {
    id: 'stud_9',
    userId: 'user_stud_9',
    name: 'Vikram Joshi',
    email: 'vikram.j@example.com',
    rollNumber: 'CS2024009',
    branch: 'Electronics & Telecom',
    year: 3,
    cgpa: 8.20,
    skills: ['React Native', 'Flutter', 'Mobile Development', 'TypeScript'],
  },
  {
    id: 'stud_10',
    userId: 'user_stud_10',
    name: 'Sneha Kulkarni',
    email: 'sneha.k@example.com',
    rollNumber: 'CS2024010',
    branch: 'Computer Engineering',
    year: 3,
    cgpa: 8.10,
    skills: ['Java', 'Spring Boot', 'SQL', 'REST APIs', 'Cybersecurity'],
  },
  {
    id: 'stud_11',
    userId: 'user_stud_11',
    name: 'Aditya Rao',
    email: 'aditya.r@example.com',
    rollNumber: 'CS2024011',
    branch: 'Computer Engineering',
    year: 3,
    cgpa: 8.05,
    skills: ['Go', 'Kubernetes', 'Docker', 'Python'],
  },
  {
    id: 'stud_12',
    userId: 'user_stud_12',
    name: 'Meera Nambiar',
    email: 'meera.n@example.com',
    rollNumber: 'CS2024012',
    branch: 'AI & Data Science',
    year: 3,
    cgpa: 7.95,
    skills: ['TypeScript', 'React', 'Node.js', 'SQL'],
  },
  {
    id: 'stud_13',
    userId: 'user_stud_13',
    name: 'Varun Bhatia',
    email: 'varun.b@example.com',
    rollNumber: 'CS2024013',
    branch: 'Information Technology',
    year: 3,
    cgpa: 7.80,
    skills: ['Java', 'Spring Boot', 'AWS', 'PostgreSQL'],
  },
  {
    id: 'stud_14',
    userId: 'user_stud_14',
    name: 'Tanvi Agarwal',
    email: 'tanvi.a@example.com',
    rollNumber: 'CS2024014',
    branch: 'Computer Engineering',
    year: 3,
    cgpa: 7.65,
    skills: ['Linux', 'Docker', 'Python', 'AWS'],
  },
  {
    id: 'stud_15',
    userId: 'user_stud_15',
    name: 'Aryan Saxena',
    email: 'aryan.s@example.com',
    rollNumber: 'CS2024015',
    branch: 'Electronics & Telecom',
    year: 3,
    cgpa: 7.50,
    skills: ['JavaScript', 'React', 'CSS', 'UI/UX'],
  },
  {
    id: 'stud_16',
    userId: 'user_stud_16',
    name: 'Kavya Reddy',
    email: 'kavya.r@example.com',
    rollNumber: 'CS2024016',
    branch: 'Information Technology',
    year: 3,
    cgpa: 7.35,
    skills: ['React Native', 'Mobile Development', 'TypeScript'],
  },
  {
    id: 'stud_17',
    userId: 'user_stud_17',
    name: 'Nikhil Pillai',
    email: 'nikhil.p@example.com',
    rollNumber: 'CS2024017',
    branch: 'Computer Engineering',
    year: 3,
    cgpa: 7.20,
    skills: ['Java', 'SQL', 'REST APIs'],
  },
  {
    id: 'stud_18',
    userId: 'user_stud_18',
    name: 'Tara Mukherjee',
    email: 'tara.m@example.com',
    rollNumber: 'CS2024018',
    branch: 'AI & Data Science',
    year: 3,
    cgpa: 7.10,
    skills: ['Python', 'Statistics'],
  },
  // Two students with lower CGPAs / narrow preferences to demonstrate unallocated edge cases
  {
    id: 'stud_19',
    userId: 'user_stud_19',
    name: 'Gaurav Singhal',
    email: 'gaurav.s@example.com',
    rollNumber: 'CS2024019',
    branch: 'Electrical Engineering',
    year: 3,
    cgpa: 6.85,
    skills: ['C', 'MATLAB', 'Circuit Simulation'],
  },
  {
    id: 'stud_20',
    userId: 'user_stud_20',
    name: 'Rhea Bansal',
    email: 'rhea.b@example.com',
    rollNumber: 'CS2024020',
    branch: 'Electronics & Telecom',
    year: 3,
    cgpa: 6.70,
    skills: ['Basic Java', 'HTML'],
  },
];

export const INITIAL_PREFERENCES: PreferenceData[] = [
  // Student 1 (Aarav - High CGPA 9.35)
  { id: 'p_1_1', studentId: 'stud_1', internshipId: 'int_goog_cloud', rank: 1 },
  { id: 'p_1_2', studentId: 'stud_1', internshipId: 'int_amzn_backend', rank: 2 },
  { id: 'p_1_3', studentId: 'stud_1', internshipId: 'int_msft_systems', rank: 3 },
  { id: 'p_1_4', studentId: 'stud_1', internshipId: 'int_amzn_devops', rank: 4 },

  // Student 2 (Ananya - High CGPA 9.15, ML specialist)
  { id: 'p_2_1', studentId: 'stud_2', internshipId: 'int_goog_ai', rank: 1 },
  { id: 'p_2_2', studentId: 'stud_2', internshipId: 'int_gs_quant', rank: 2 },
  { id: 'p_2_3', studentId: 'stud_2', internshipId: 'int_goog_cloud', rank: 3 },

  // Student 3 (Rohan - 8.85)
  { id: 'p_3_1', studentId: 'stud_3', internshipId: 'int_msft_fullstack', rank: 1 },
  { id: 'p_3_2', studentId: 'stud_3', internshipId: 'int_adobe_frontend', rank: 2 },
  { id: 'p_3_3', studentId: 'stud_3', internshipId: 'int_amzn_backend', rank: 3 },

  // Student 4 (Priya - 8.95 Quant)
  { id: 'p_4_1', studentId: 'stud_4', internshipId: 'int_gs_quant', rank: 1 },
  { id: 'p_4_2', studentId: 'stud_4', internshipId: 'int_goog_ai', rank: 2 },
  { id: 'p_4_3', studentId: 'stud_4', internshipId: 'int_gs_fintech', rank: 3 },

  // Student 5 (Kabir - 8.70 Backend)
  { id: 'p_5_1', studentId: 'stud_5', internshipId: 'int_amzn_backend', rank: 1 },
  { id: 'p_5_2', studentId: 'stud_5', internshipId: 'int_msft_fullstack', rank: 2 },
  { id: 'p_5_3', studentId: 'stud_5', internshipId: 'int_gs_fintech', rank: 3 },

  // Student 6 (Isha - 8.60 Systems)
  { id: 'p_6_1', studentId: 'stud_6', internshipId: 'int_msft_systems', rank: 1 },
  { id: 'p_6_2', studentId: 'stud_6', internshipId: 'int_goog_cloud', rank: 2 },
  { id: 'p_6_3', studentId: 'stud_6', internshipId: 'int_amzn_backend', rank: 3 },

  // Student 7 (Siddharth - 8.45 Frontend)
  { id: 'p_7_1', studentId: 'stud_7', internshipId: 'int_adobe_frontend', rank: 1 },
  { id: 'p_7_2', studentId: 'stud_7', internshipId: 'int_msft_fullstack', rank: 2 },
  { id: 'p_7_3', studentId: 'stud_7', internshipId: 'int_adobe_mobile', rank: 3 },

  // Student 8 (Diya - 8.30 DevOps)
  { id: 'p_8_1', studentId: 'stud_8', internshipId: 'int_amzn_devops', rank: 1 },
  { id: 'p_8_2', studentId: 'stud_8', internshipId: 'int_goog_cloud', rank: 2 },
  { id: 'p_8_3', studentId: 'stud_8', internshipId: 'int_amzn_backend', rank: 3 },

  // Student 9 (Vikram - 8.20 Mobile)
  { id: 'p_9_1', studentId: 'stud_9', internshipId: 'int_adobe_mobile', rank: 1 },
  { id: 'p_9_2', studentId: 'stud_9', internshipId: 'int_adobe_frontend', rank: 2 },
  { id: 'p_9_3', studentId: 'stud_9', internshipId: 'int_msft_fullstack', rank: 3 },

  // Student 10 (Sneha - 8.10 FinTech)
  { id: 'p_10_1', studentId: 'stud_10', internshipId: 'int_gs_fintech', rank: 1 },
  { id: 'p_10_2', studentId: 'stud_10', internshipId: 'int_amzn_backend', rank: 2 },
  { id: 'p_10_3', studentId: 'stud_10', internshipId: 'int_msft_fullstack', rank: 3 },

  // Student 11 (Aditya - 8.05 Cloud)
  { id: 'p_11_1', studentId: 'stud_11', internshipId: 'int_goog_cloud', rank: 1 },
  { id: 'p_11_2', studentId: 'stud_11', internshipId: 'int_amzn_devops', rank: 2 },
  { id: 'p_11_3', studentId: 'stud_11', internshipId: 'int_amzn_backend', rank: 3 },

  // Student 12 (Meera - 7.95 Fullstack)
  { id: 'p_12_1', studentId: 'stud_12', internshipId: 'int_msft_fullstack', rank: 1 },
  { id: 'p_12_2', studentId: 'stud_12', internshipId: 'int_adobe_frontend', rank: 2 },
  { id: 'p_12_3', studentId: 'stud_12', internshipId: 'int_adobe_mobile', rank: 3 },

  // Student 13 (Varun - 7.80 Backend)
  { id: 'p_13_1', studentId: 'stud_13', internshipId: 'int_amzn_backend', rank: 1 },
  { id: 'p_13_2', studentId: 'stud_13', internshipId: 'int_gs_fintech', rank: 2 },
  { id: 'p_13_3', studentId: 'stud_13', internshipId: 'int_amzn_devops', rank: 3 },

  // Student 14 (Tanvi - 7.65 DevOps)
  { id: 'p_14_1', studentId: 'stud_14', internshipId: 'int_amzn_devops', rank: 1 },
  { id: 'p_14_2', studentId: 'stud_14', internshipId: 'int_msft_fullstack', rank: 2 },
  { id: 'p_14_3', studentId: 'stud_14', internshipId: 'int_adobe_mobile', rank: 3 },

  // Student 15 (Aryan - 7.50 Frontend)
  { id: 'p_15_1', studentId: 'stud_15', internshipId: 'int_adobe_frontend', rank: 1 },
  { id: 'p_15_2', studentId: 'stud_15', internshipId: 'int_adobe_mobile', rank: 2 },

  // Student 16 (Kavya - 7.35 Mobile)
  { id: 'p_16_1', studentId: 'stud_16', internshipId: 'int_adobe_mobile', rank: 1 },
  { id: 'p_16_2', studentId: 'stud_16', internshipId: 'int_adobe_frontend', rank: 2 },

  // Student 17 (Nikhil - 7.20 FinTech)
  { id: 'p_17_1', studentId: 'stud_17', internshipId: 'int_gs_fintech', rank: 1 },
  { id: 'p_17_2', studentId: 'stud_17', internshipId: 'int_adobe_mobile', rank: 2 },

  // Student 18 (Tara - 7.10 Data Science)
  { id: 'p_18_1', studentId: 'stud_18', internshipId: 'int_gs_quant', rank: 1 }, // Ineligible (min CGPA 8.5)
  { id: 'p_18_2', studentId: 'stud_18', internshipId: 'int_goog_ai', rank: 2 }, // Ineligible (min CGPA 8.8)
  { id: 'p_18_3', studentId: 'stud_18', internshipId: 'int_adobe_mobile', rank: 3 },

  // Student 19 (Gaurav - 6.85, applies only to high CGPA roles)
  { id: 'p_19_1', studentId: 'stud_19', internshipId: 'int_goog_cloud', rank: 1 }, // Ineligible (min 8.5)
  { id: 'p_19_2', studentId: 'stud_19', internshipId: 'int_msft_systems', rank: 2 }, // Ineligible (min 8.0)

  // Student 20 (Rhea - 6.70, only applies to Google AI)
  { id: 'p_20_1', studentId: 'stud_20', internshipId: 'int_goog_ai', rank: 1 }, // Ineligible (min 8.8)
];
