import { UserSession, StudentData, CompanyData, InternshipData, PreferenceData } from '../types';

export const INITIAL_COMPANIES: CompanyData[] = [
  {
    id: 'comp_google',
    name: 'Google India',
    description: 'Global leader in internet search, cloud computing, distributed systems infrastructure, and artificial intelligence.',
    logoUrl: 'https://images.unsplash.com/photo-1572021335469-31706a17aaef?w=128&auto=format&fit=crop&q=80',
    website: 'https://careers.google.com',
    industry: 'Internet & Cloud Software',
    location: 'Bangalore, Karnataka',
  },
  {
    id: 'comp_msft',
    name: 'Microsoft IDC',
    description: 'Empowering every person and organization to achieve more through cloud infrastructure, developer tooling, and enterprise AI.',
    logoUrl: 'https://images.unsplash.com/photo-1642104704074-907c0698cbd9?w=128&auto=format&fit=crop&q=80',
    website: 'https://careers.microsoft.com',
    industry: 'Enterprise Cloud & Operating Systems',
    location: 'Hyderabad, Telangana',
  },
  {
    id: 'comp_amazon',
    name: 'Amazon Development Centre',
    description: 'Pioneering planetary-scale distributed systems, AWS cloud architectures, robotics logistics, and high-frequency transactions.',
    logoUrl: 'https://images.unsplash.com/photo-1523474255658-4af61b1684c3?w=128&auto=format&fit=crop&q=80',
    website: 'https://amazon.jobs',
    industry: 'Cloud Computing & E-Commerce',
    location: 'Bangalore, Karnataka',
  },
  {
    id: 'comp_adobe',
    name: 'Adobe',
    description: 'Changing the world through digital experiences, creative cloud suites, document processing, and generative visual AI.',
    logoUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=128&auto=format&fit=crop&q=80',
    website: 'https://adobe.com/careers',
    industry: 'Creative Software & Visual AI',
    location: 'Noida, Uttar Pradesh',
  },
  {
    id: 'comp_tcs',
    name: 'TCS',
    description: 'Global IT consulting, digital engineering, and enterprise systems modernization partner operating in 50+ countries.',
    logoUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=128&auto=format&fit=crop&q=80',
    website: 'https://tcs.com/careers',
    industry: 'IT Consulting & Enterprise Modernization',
    location: 'Mumbai, Maharashtra',
  },
];

export const INITIAL_INTERNSHIPS: InternshipData[] = [
  {
    id: 'int_g_cloud',
    companyId: 'comp_google',
    companyName: 'Google India',
    title: 'Cloud Systems Engineering Intern',
    description: 'Build distributed microservices, containerized control planes, and high-throughput networking pipelines for Google Cloud Platform.',
    location: 'Bangalore, Karnataka',
    mode: 'HYBRID',
    stipend: 85000,
    duration: '6 Months',
    minimumCGPA: 8.5,
    allowedBranches: ['Computer Science', 'Information Technology', 'Artificial Intelligence & Data Science'],
    requiredSkills: ['Go', 'Kubernetes', 'Docker', 'Distributed Systems', 'Python'],
    totalSeats: 2,
    availableSeats: 2,
    applicationDeadline: '2026-12-31',
    status: 'ACTIVE',
  },
  {
    id: 'int_g_ai',
    companyId: 'comp_google',
    companyName: 'Google India',
    title: 'AI & Machine Learning Research Intern',
    description: 'Develop and evaluate transformer architectures, foundation model alignment, and statistical optimization routines with Google Research.',
    location: 'Bangalore, Karnataka',
    mode: 'HYBRID',
    stipend: 90000,
    duration: '6 Months',
    minimumCGPA: 8.8,
    allowedBranches: ['Computer Science', 'Artificial Intelligence & Data Science'],
    requiredSkills: ['Python', 'PyTorch', 'TensorFlow', 'Deep Learning', 'Algorithms'],
    totalSeats: 1,
    availableSeats: 1,
    applicationDeadline: '2026-12-31',
    status: 'ACTIVE',
  },
  {
    id: 'int_ms_fullstack',
    companyId: 'comp_msft',
    companyName: 'Microsoft IDC',
    title: 'Full Stack Azure Developer Intern',
    description: 'Design and deploy modern cloud portals using TypeScript, React, Azure Functions, and scalable relational data stores.',
    location: 'Hyderabad, Telangana',
    mode: 'REMOTE',
    stipend: 75000,
    duration: '3 Months',
    minimumCGPA: 8.0,
    allowedBranches: ['Computer Science', 'Information Technology', 'Electronics & Communication'],
    requiredSkills: ['TypeScript', 'React', 'Node.js', 'Azure', 'SQL'],
    totalSeats: 2,
    availableSeats: 2,
    applicationDeadline: '2026-12-31',
    status: 'ACTIVE',
  },
  {
    id: 'int_ms_data',
    companyId: 'comp_msft',
    companyName: 'Microsoft IDC',
    title: 'Data Platform & Analytics Intern',
    description: 'Design analytical lakehouse streaming pipelines, SQL transformation graphs, and telemetry aggregation systems on Azure Synapse.',
    location: 'Hyderabad, Telangana',
    mode: 'HYBRID',
    stipend: 72000,
    duration: '6 Months',
    minimumCGPA: 7.8,
    allowedBranches: ['Computer Science', 'Information Technology', 'Artificial Intelligence & Data Science', 'Electronics & Communication'],
    requiredSkills: ['Python', 'SQL', 'Spark', 'Data Modeling', 'PowerBI'],
    totalSeats: 2,
    availableSeats: 2,
    applicationDeadline: '2026-12-31',
    status: 'ACTIVE',
  },
  {
    id: 'int_amz_sde',
    companyId: 'comp_amazon',
    companyName: 'Amazon Development Centre',
    title: 'Software Development Engineer Intern',
    description: 'Engineer high-throughput transactional backends, low-latency queues, and fault-tolerant cloud services on AWS.',
    location: 'Bangalore, Karnataka',
    mode: 'ONSITE',
    stipend: 80000,
    duration: '6 Months',
    minimumCGPA: 8.2,
    allowedBranches: ['Computer Science', 'Information Technology'],
    requiredSkills: ['Java', 'Spring Boot', 'AWS', 'Data Structures', 'DynamoDB'],
    totalSeats: 2,
    availableSeats: 2,
    applicationDeadline: '2026-12-31',
    status: 'ACTIVE',
  },
  {
    id: 'int_amz_devops',
    companyId: 'comp_amazon',
    companyName: 'Amazon Development Centre',
    title: 'DevOps & Site Reliability Intern',
    description: 'Automate CI/CD pipelines, container orchestration, Linux systems observability, and infrastructure-as-code on AWS.',
    location: 'Chennai, Tamil Nadu',
    mode: 'HYBRID',
    stipend: 68000,
    duration: '3 Months',
    minimumCGPA: 7.5,
    allowedBranches: ['Computer Science', 'Information Technology', 'Electronics & Communication'],
    requiredSkills: ['Linux', 'AWS', 'Terraform', 'Docker', 'Bash'],
    totalSeats: 2,
    availableSeats: 2,
    applicationDeadline: '2026-12-31',
    status: 'ACTIVE',
  },
  {
    id: 'int_adb_frontend',
    companyId: 'comp_adobe',
    companyName: 'Adobe',
    title: 'Design Systems & Frontend Intern',
    description: 'Craft pixel-perfect, accessible UI components, interactive canvases, and modern web application interfaces for creative cloud suites.',
    location: 'Noida, Uttar Pradesh',
    mode: 'REMOTE',
    stipend: 70000,
    duration: '3 Months',
    minimumCGPA: 7.5,
    allowedBranches: ['Computer Science', 'Information Technology', 'Electronics & Communication'],
    requiredSkills: ['React', 'TypeScript', 'Tailwind CSS', 'Next.js', 'Web Standards'],
    totalSeats: 2,
    availableSeats: 2,
    applicationDeadline: '2026-12-31',
    status: 'ACTIVE',
  },
  {
    id: 'int_adb_cv',
    companyId: 'comp_adobe',
    companyName: 'Adobe',
    title: 'Computer Vision & Multimedia Intern',
    description: 'Implement real-time neural filter algorithms, segmentation models, and GPU-accelerated image manipulation pipelines.',
    location: 'Noida, Uttar Pradesh',
    mode: 'HYBRID',
    stipend: 78000,
    duration: '6 Months',
    minimumCGPA: 8.3,
    allowedBranches: ['Computer Science', 'Artificial Intelligence & Data Science', 'Electronics & Communication'],
    requiredSkills: ['C++', 'OpenCV', 'Python', 'Computer Vision', 'Machine Learning'],
    totalSeats: 1,
    availableSeats: 1,
    applicationDeadline: '2026-12-31',
    status: 'ACTIVE',
  },
  {
    id: 'int_tcs_digital',
    companyId: 'comp_tcs',
    companyName: 'TCS',
    title: 'Digital Enterprise Software Intern',
    description: 'Develop enterprise REST APIs, web portals, and microservices for banking, healthcare, and retail clients.',
    location: 'Mumbai, Maharashtra',
    mode: 'HYBRID',
    stipend: 45000,
    duration: '3 Months',
    minimumCGPA: 6.5,
    allowedBranches: ['All Branches'],
    requiredSkills: ['Java', 'SQL', 'HTML', 'JavaScript', 'Spring'],
    totalSeats: 3,
    availableSeats: 3,
    applicationDeadline: '2026-12-31',
    status: 'ACTIVE',
  },
  {
    id: 'int_tcs_embed',
    companyId: 'comp_tcs',
    companyName: 'TCS',
    title: 'IoT & Embedded Systems Intern',
    description: 'Program real-time firmware, telemetry sensor nodes, microcontrollers, and communication protocols for industrial automation.',
    location: 'Pune, Maharashtra',
    mode: 'ONSITE',
    stipend: 42000,
    duration: '3 Months',
    minimumCGPA: 6.8,
    allowedBranches: ['Electronics & Communication', 'Mechanical Engineering'],
    requiredSkills: ['Embedded C', 'Microcontrollers', 'RTOS', 'IoT', 'Sensors'],
    totalSeats: 2,
    availableSeats: 2,
    applicationDeadline: '2026-12-31',
    status: 'ACTIVE',
  },
];

export const INITIAL_STUDENTS: StudentData[] = [
  {
    id: 'stud_1',
    userId: 'user_stud_1',
    name: 'Aarav Sharma',
    email: 'student@example.com', // Demo login account
    rollNumber: 'CS2024001',
    branch: 'Computer Science',
    year: 3,
    graduationYear: 2026,
    cgpa: 9.40,
    experienceMonths: 8,
    experienceSummary: 'Open-source contributor to Kubernetes operators; built distributed caching systems.',
    skills: ['Go', 'Kubernetes', 'Docker', 'Python', 'Distributed Systems'],
    resumeUrl: 'https://example.com/resumes/aarav.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_2',
    userId: 'user_stud_2',
    name: 'Priya Patel',
    email: 'priya@example.com',
    rollNumber: 'CS2024002',
    branch: 'Computer Science',
    year: 3,
    graduationYear: 2026,
    cgpa: 9.15,
    experienceMonths: 6,
    experienceSummary: 'Published conference paper on Vision Transformers and deep reinforcement learning.',
    skills: ['Python', 'PyTorch', 'Deep Learning', 'TensorFlow', 'Algorithms'],
    resumeUrl: 'https://example.com/resumes/priya.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_3',
    userId: 'user_stud_3',
    name: 'Rohan Verma',
    email: 'rohan@example.com',
    rollNumber: 'IT2024003',
    branch: 'Information Technology',
    year: 3,
    graduationYear: 2026,
    cgpa: 8.85,
    experienceMonths: 6,
    experienceSummary: 'Built high-throughput GraphQL APIs and Next.js portals at a fintech startup.',
    skills: ['TypeScript', 'React', 'Node.js', 'SQL', 'Azure'],
    resumeUrl: 'https://example.com/resumes/rohan.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_4',
    userId: 'user_stud_4',
    name: 'Ananya Iyer',
    email: 'ananya@example.com',
    rollNumber: 'CS2024004',
    branch: 'Computer Science',
    year: 3,
    graduationYear: 2026,
    cgpa: 8.90,
    experienceMonths: 7,
    experienceSummary: 'Specialized in event-driven Java Spring Boot microservices and DynamoDB backends.',
    skills: ['Java', 'Spring Boot', 'AWS', 'Data Structures', 'DynamoDB'],
    resumeUrl: 'https://example.com/resumes/ananya.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_5',
    userId: 'user_stud_5',
    name: 'Kabir Mehta',
    email: 'kabir@example.com',
    rollNumber: 'AI2024005',
    branch: 'Artificial Intelligence & Data Science',
    year: 3,
    graduationYear: 2026,
    cgpa: 9.05,
    experienceMonths: 5,
    experienceSummary: 'Researched low-latency video super-resolution using PyTorch and OpenCV.',
    skills: ['Python', 'PyTorch', 'Computer Vision', 'OpenCV', 'Machine Learning'],
    resumeUrl: 'https://example.com/resumes/kabir.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_6',
    userId: 'user_stud_6',
    name: 'Ishita Rao',
    email: 'ishita@example.com',
    rollNumber: 'CS2024006',
    branch: 'Computer Science',
    year: 3,
    graduationYear: 2026,
    cgpa: 8.40,
    experienceMonths: 4,
    experienceSummary: 'Frontend engineer with passion for accessible design systems and Tailwind UI.',
    skills: ['React', 'TypeScript', 'Next.js', 'Tailwind CSS', 'Web Standards'],
    resumeUrl: 'https://example.com/resumes/ishita.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_7',
    userId: 'user_stud_7',
    name: 'Aditya Nair',
    email: 'aditya@example.com',
    rollNumber: 'EC2024007',
    branch: 'Electronics & Communication',
    year: 3,
    graduationYear: 2026,
    cgpa: 8.10,
    experienceMonths: 4,
    experienceSummary: 'Built automated cloud testing harnesses and Terraform blueprints on AWS.',
    skills: ['Linux', 'AWS', 'Terraform', 'Docker', 'Bash'],
    resumeUrl: 'https://example.com/resumes/aditya.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_8',
    userId: 'user_stud_8',
    name: 'Sneha Kulkarni',
    email: 'sneha@example.com',
    rollNumber: 'IT2024008',
    branch: 'Information Technology',
    year: 3,
    graduationYear: 2026,
    cgpa: 8.25,
    experienceMonths: 4,
    experienceSummary: 'Data engineering intern working with Spark pipelines and cloud data warehouses.',
    skills: ['Python', 'SQL', 'Spark', 'Data Modeling', 'PowerBI'],
    resumeUrl: 'https://example.com/resumes/sneha.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_9',
    userId: 'user_stud_9',
    name: 'Vikram Sen',
    email: 'vikram@example.com',
    rollNumber: 'CS2024009',
    branch: 'Computer Science',
    year: 3,
    graduationYear: 2026,
    cgpa: 8.60,
    experienceMonths: 5,
    experienceSummary: 'Systems researcher focused on container runtime isolation and Linux networking.',
    skills: ['Go', 'Docker', 'Kubernetes', 'Linux', 'Python'],
    resumeUrl: 'https://example.com/resumes/vikram.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_10',
    userId: 'user_stud_10',
    name: 'Neha Gupta',
    email: 'neha@example.com',
    rollNumber: 'AI2024010',
    branch: 'Artificial Intelligence & Data Science',
    year: 3,
    graduationYear: 2026,
    cgpa: 8.70,
    experienceMonths: 4,
    experienceSummary: 'Developed predictive feature pipelines and interactive BI dashboards.',
    skills: ['Python', 'SQL', 'PyTorch', 'Data Modeling', 'Machine Learning'],
    resumeUrl: 'https://example.com/resumes/neha.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_11',
    userId: 'user_stud_11',
    name: 'Arjun Reddy',
    email: 'arjun@example.com',
    rollNumber: 'CS2024011',
    branch: 'Computer Science',
    year: 3,
    graduationYear: 2026,
    cgpa: 8.35,
    experienceMonths: 4,
    experienceSummary: 'Core Java engineer with extensive knowledge of data structures and Spring APIs.',
    skills: ['Java', 'Spring Boot', 'SQL', 'AWS', 'Data Structures'],
    resumeUrl: 'https://example.com/resumes/arjun.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_12',
    userId: 'user_stud_12',
    name: 'Tanvi Joshi',
    email: 'tanvi@example.com',
    rollNumber: 'IT2024012',
    branch: 'Information Technology',
    year: 3,
    graduationYear: 2026,
    cgpa: 7.95,
    experienceMonths: 3,
    experienceSummary: 'Created responsive frontend portfolios and component libraries using Next.js.',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Node.js', 'SQL'],
    resumeUrl: 'https://example.com/resumes/tanvi.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_13',
    userId: 'user_stud_13',
    name: 'Siddharth Bose',
    email: 'siddharth@example.com',
    rollNumber: 'EC2024013',
    branch: 'Electronics & Communication',
    year: 3,
    graduationYear: 2026,
    cgpa: 7.80,
    experienceMonths: 4,
    experienceSummary: 'Embedded developer with hands-on RTOS and ESP32 industrial telemetry designs.',
    skills: ['Embedded C', 'Microcontrollers', 'RTOS', 'IoT', 'Sensors'],
    resumeUrl: 'https://example.com/resumes/siddharth.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_14',
    userId: 'user_stud_14',
    name: 'Divya Menon',
    email: 'divya@example.com',
    rollNumber: 'AI2024014',
    branch: 'Artificial Intelligence & Data Science',
    year: 3,
    graduationYear: 2026,
    cgpa: 8.50,
    experienceMonths: 4,
    experienceSummary: 'Trained convolutional neural nets for diagnostic medical image processing.',
    skills: ['C++', 'OpenCV', 'Python', 'Computer Vision', 'Machine Learning'],
    resumeUrl: 'https://example.com/resumes/divya.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_15',
    userId: 'user_stud_15',
    name: 'Varun Kapoor',
    email: 'varun@example.com',
    rollNumber: 'CS2024015',
    branch: 'Computer Science',
    year: 3,
    graduationYear: 2026,
    cgpa: 7.60,
    experienceMonths: 2,
    experienceSummary: 'Hands-on Linux server administration and automated Docker container orchestration.',
    skills: ['Linux', 'AWS', 'Docker', 'Python', 'SQL'],
    resumeUrl: 'https://example.com/resumes/varun.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_16',
    userId: 'user_stud_16',
    name: 'Pooja Hegde',
    email: 'pooja@example.com',
    rollNumber: 'IT2024016',
    branch: 'Information Technology',
    year: 3,
    graduationYear: 2026,
    cgpa: 7.45,
    experienceMonths: 2,
    experienceSummary: 'Backend developer with foundational experience in Spring Boot and MySQL.',
    skills: ['Java', 'Spring', 'SQL', 'JavaScript', 'HTML'],
    resumeUrl: 'https://example.com/resumes/pooja.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_17',
    userId: 'user_stud_17',
    name: 'Kunal Deshmukh',
    email: 'kunal@example.com',
    rollNumber: 'EC2024017',
    branch: 'Electronics & Communication',
    year: 3,
    graduationYear: 2026,
    cgpa: 7.30,
    experienceMonths: 2,
    experienceSummary: 'Firmware hacker working on CAN bus protocols, telemetry, and ARM Cortex MCUs.',
    skills: ['Embedded C', 'Microcontrollers', 'RTOS', 'IoT', 'Sensors'],
    resumeUrl: 'https://example.com/resumes/kunal.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_18',
    userId: 'user_stud_18',
    name: 'Riya Bhattacharya',
    email: 'riya@example.com',
    rollNumber: 'ME2024018',
    branch: 'Mechanical Engineering',
    year: 3,
    graduationYear: 2026,
    cgpa: 7.10,
    experienceMonths: 1,
    experienceSummary: 'Robotics automation enthusiast with IoT sensor network prototypes.',
    skills: ['IoT', 'Embedded C', 'Microcontrollers', 'Sensors', 'Python'],
    resumeUrl: 'https://example.com/resumes/riya.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_19',
    userId: 'user_stud_19',
    name: 'Gaurav Gill',
    email: 'gaurav@example.com',
    rollNumber: 'CS2024019',
    branch: 'Computer Science',
    year: 3,
    graduationYear: 2026,
    cgpa: 6.90,
    experienceMonths: 1,
    experienceSummary: 'Core Java programmer with strong object-oriented design and web fundamentals.',
    skills: ['Java', 'SQL', 'HTML', 'JavaScript', 'Spring'],
    resumeUrl: 'https://example.com/resumes/gaurav.pdf',
    preferencesLocked: true,
  },
  {
    id: 'stud_20',
    userId: 'user_stud_20',
    name: 'Meera Pillai',
    email: 'meera@example.com',
    rollNumber: 'ME2024020',
    branch: 'Mechanical Engineering',
    year: 3,
    graduationYear: 2026,
    cgpa: 6.75,
    experienceMonths: 1,
    experienceSummary: 'Industrial automation engineer with foundational Java and web API training.',
    skills: ['SQL', 'Java', 'HTML', 'JavaScript', 'Spring'],
    resumeUrl: 'https://example.com/resumes/meera.pdf',
    preferencesLocked: true,
  },
];

export const INITIAL_PREFERENCES: PreferenceData[] = [
  // Student 1 (Top Cloud candidate)
  { id: 'p_1_1', studentId: 'stud_1', internshipId: 'int_g_cloud', rank: 1 },
  { id: 'p_1_2', studentId: 'stud_1', internshipId: 'int_amz_sde', rank: 2 },
  { id: 'p_1_3', studentId: 'stud_1', internshipId: 'int_ms_fullstack', rank: 3 },

  // Student 2 (Top AI candidate)
  { id: 'p_2_1', studentId: 'stud_2', internshipId: 'int_g_ai', rank: 1 },
  { id: 'p_2_2', studentId: 'stud_2', internshipId: 'int_adb_cv', rank: 2 },
  { id: 'p_2_3', studentId: 'stud_2', internshipId: 'int_g_cloud', rank: 3 },

  // Student 3 (Full stack candidate)
  { id: 'p_3_1', studentId: 'stud_3', internshipId: 'int_ms_fullstack', rank: 1 },
  { id: 'p_3_2', studentId: 'stud_3', internshipId: 'int_adb_frontend', rank: 2 },
  { id: 'p_3_3', studentId: 'stud_3', internshipId: 'int_amz_sde', rank: 3 },

  // Student 4 (Amazon SDE preferred)
  { id: 'p_4_1', studentId: 'stud_4', internshipId: 'int_amz_sde', rank: 1 },
  { id: 'p_4_2', studentId: 'stud_4', internshipId: 'int_ms_fullstack', rank: 2 },
  { id: 'p_4_3', studentId: 'stud_4', internshipId: 'int_g_cloud', rank: 3 },

  // Student 5 (AI / Vision specialist)
  { id: 'p_5_1', studentId: 'stud_5', internshipId: 'int_g_ai', rank: 1 },
  { id: 'p_5_2', studentId: 'stud_5', internshipId: 'int_adb_cv', rank: 2 },
  { id: 'p_5_3', studentId: 'stud_5', internshipId: 'int_ms_data', rank: 3 },

  // Student 6 (Frontend specialist)
  { id: 'p_6_1', studentId: 'stud_6', internshipId: 'int_adb_frontend', rank: 1 },
  { id: 'p_6_2', studentId: 'stud_6', internshipId: 'int_ms_fullstack', rank: 2 },
  { id: 'p_6_3', studentId: 'stud_6', internshipId: 'int_tcs_digital', rank: 3 },

  // Student 7 (DevOps / SRE specialist)
  { id: 'p_7_1', studentId: 'stud_7', internshipId: 'int_amz_devops', rank: 1 },
  { id: 'p_7_2', studentId: 'stud_7', internshipId: 'int_ms_data', rank: 2 },
  { id: 'p_7_3', studentId: 'stud_7', internshipId: 'int_tcs_digital', rank: 3 },

  // Student 8 (Data & Analytics)
  { id: 'p_8_1', studentId: 'stud_8', internshipId: 'int_ms_data', rank: 1 },
  { id: 'p_8_2', studentId: 'stud_8', internshipId: 'int_amz_sde', rank: 2 },
  { id: 'p_8_3', studentId: 'stud_8', internshipId: 'int_tcs_digital', rank: 3 },

  // Student 9 (Cloud Systems)
  { id: 'p_9_1', studentId: 'stud_9', internshipId: 'int_g_cloud', rank: 1 },
  { id: 'p_9_2', studentId: 'stud_9', internshipId: 'int_amz_devops', rank: 2 },
  { id: 'p_9_3', studentId: 'stud_9', internshipId: 'int_ms_fullstack', rank: 3 },

  // Student 10 (Data & Analytics)
  { id: 'p_10_1', studentId: 'stud_10', internshipId: 'int_ms_data', rank: 1 },
  { id: 'p_10_2', studentId: 'stud_10', internshipId: 'int_adb_cv', rank: 2 },
  { id: 'p_10_3', studentId: 'stud_10', internshipId: 'int_tcs_digital', rank: 3 },

  // Student 11 (Amazon SDE)
  { id: 'p_11_1', studentId: 'stud_11', internshipId: 'int_amz_sde', rank: 1 },
  { id: 'p_11_2', studentId: 'stud_11', internshipId: 'int_ms_fullstack', rank: 2 },
  { id: 'p_11_3', studentId: 'stud_11', internshipId: 'int_tcs_digital', rank: 3 },

  // Student 12 (Frontend)
  { id: 'p_12_1', studentId: 'stud_12', internshipId: 'int_adb_frontend', rank: 1 },
  { id: 'p_12_2', studentId: 'stud_12', internshipId: 'int_ms_fullstack', rank: 2 },
  { id: 'p_12_3', studentId: 'stud_12', internshipId: 'int_tcs_digital', rank: 3 },

  // Student 13 (IoT / Embedded)
  { id: 'p_13_1', studentId: 'stud_13', internshipId: 'int_tcs_embed', rank: 1 },
  { id: 'p_13_2', studentId: 'stud_13', internshipId: 'int_tcs_digital', rank: 2 },

  // Student 14 (Computer Vision)
  { id: 'p_14_1', studentId: 'stud_14', internshipId: 'int_adb_cv', rank: 1 },
  { id: 'p_14_2', studentId: 'stud_14', internshipId: 'int_ms_data', rank: 2 },
  { id: 'p_14_3', studentId: 'stud_14', internshipId: 'int_tcs_digital', rank: 3 },

  // Student 15 (DevOps)
  { id: 'p_15_1', studentId: 'stud_15', internshipId: 'int_amz_devops', rank: 1 },
  { id: 'p_15_2', studentId: 'stud_15', internshipId: 'int_tcs_digital', rank: 2 },

  // Student 16 (Enterprise IT)
  { id: 'p_16_1', studentId: 'stud_16', internshipId: 'int_tcs_digital', rank: 1 },

  // Student 17 (Embedded IoT)
  { id: 'p_17_1', studentId: 'stud_17', internshipId: 'int_tcs_embed', rank: 1 },
  { id: 'p_17_2', studentId: 'stud_17', internshipId: 'int_tcs_digital', rank: 2 },

  // Student 18 (Mechanical IoT)
  { id: 'p_18_1', studentId: 'stud_18', internshipId: 'int_tcs_embed', rank: 1 },
  { id: 'p_18_2', studentId: 'stud_18', internshipId: 'int_tcs_digital', rank: 2 },

  // Student 19 (Digital IT)
  { id: 'p_19_1', studentId: 'stud_19', internshipId: 'int_tcs_digital', rank: 1 },

  // Student 20 (Digital IT)
  { id: 'p_20_1', studentId: 'stud_20', internshipId: 'int_tcs_digital', rank: 1 },
];
